options:
  formatter: stylish
files:
  include:
    - "./src/assets/**/*.s+(a|c)ss"
  ignore: "./src/assets/js/components/chord/**/*.s+(a|c)ss"
rules:
  attribute-quotes: 1
  border-zero: 1
  no-important: 1
  leading-zero: 0
  no-color-keywords: 1
  no-css-comments: 1
  no-empty-rulesets: 1
  no-ids: 1
  no-invalid-hex: 1
  no-trailing-whitespace: 1
  no-universal-selectors: 1
  no-vendor-prefixes: 1
  no-url-domains: 1
  url-quotes: 1
  empty-line-between-blocks: 0
  shorthand-values: 1
  space-after-comma: 1
  space-around-operator: 1
  trailing-semicolon: 1
  final-newline: 1
  property-sort-order: 0
  no-color-literals: 0
  one-declaration-per-line: 0
  single-line-per-selector: 0
  pseudo-element: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  force-attribute-nesting: 0
  variable-name-format: 0
  extends-before-declarations: 0
  mixins-before-declarations: 0
  brace-style: 0
  class-name-format:
    - 1
    - convention: ^[a-z]([a-zA-Z]*)(-[a-z0-9]([a-zA-Z]*))*(--[a-z0-9]([a-zA-Z]*))*$
      convention-explanation: "Class must be follow componentName-childName--modfierName"
      allow-leading-underscore: false
  space-before-brace:
    - 1
    - include: 1
  space-after-colon:
    - 1
    - include: true
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 1
    - size: 2
  quotes:
    - 1
    - style: double
  no-duplicate-properties:
    - 1
    - exclude:
        - display
        - background-image
        - composes
  no-misspelled-properties:
    - 1
    - "extra-properties":
        - "overflow-scrolling"
        - composes
  no-disallowed-properties:
    - 1
    - "properties":
        - "overflow-scrolling"
  clean-import-paths:
    - 0
    - leading-underscore: 0
      filename-extension: 0
